### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by mairajha** [hrfee/jellyfin-accounts#39]
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "c:\python38\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "c:\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002765544D160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jellyfin.local', port=8096): Max retries exceeded with url: /emby/Users/AuthenticateByName?Username=username&Pw=password (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002765544D160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\jf-accounts.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\jellyfin_accounts\__init__.py", line 316, in main
    import jellyfin_accounts.web_api
  File "c:\python38\lib\site-packages\jellyfin_accounts\web_api.py", line 103, in <module>
    jf.authenticate(config["jellyfin"]["username"], config["jellyfin"]["password"])
  File "c:\python38\lib\site-packages\jellyfin_accounts\jf_api.py", line 166, in authenticate
    response = requests.post(
  File "c:\python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jellyfin.local', port=8096): Max retries exceeded with url: /emby/Users/AuthenticateByName?Username=username&Pw=password (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002765544D160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by hrfee** [comment]
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='jellyfin.local', port=8096)`

looks like it couldn't connect to your jellyfin instance. ill close this since you seem to have got it working anyway.

**Comment by mairajha** [comment]
managed jellyfin-accounts to work but still unable to launch it properly as I am stuck on page#3 where I have to enter jellyfin server details along with user id and password (it says failed)
 - in jf-go I have above mentioned issue still persist.

**Comment by hrfee** [comment]
could you open an issue on the other repo instead then? thanks. Also, check the console output of the program. It should give you an error, add that to the issue.

**Comment by mairajha** [comment]
![jf-accounts1](https://user-images.githubusercontent.com/52917522/98987378-f51a9d80-2547-11eb-939b-59993b776c44.jpg)
it would be great if you will guide me on this?

**Comment by hrfee** [comment]
update first, that's an old version, and create a new issue on the other repo with the output of the program (from the console), which should include an error.
